package com.j1987.aakura.domain;

public enum JEvent {

    NEW_COMPANY, UPDATE_COMPANY, DELETE_COMPANY,
    
    NEW_ACTIVITY, UPDATE_ACTIVITY, DELETE_ACTIVITY,
    
    UPDATE_PASSWORD,
    
    NEW_ROLE,     
    
    NEW_USER, UPDATE_USER, DELETE_USER, ASSIGNROLE_USER, ASSIGNACTIVITY_USER, UNASSIGN_USER,
    
    NEW_PAYMENT, UPDATE_PAYMENT, DELETE_PAYMENT,
    
    LOGIN_USER, LOGOUT_USER;
}
