// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.aakura.domain;

import com.j1987.aakura.domain.JActivity;
import com.j1987.aakura.domain.JActivityDataOnDemand;
import com.j1987.aakura.domain.JCompanyDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect JActivityDataOnDemand_Roo_DataOnDemand {
    
    declare @type: JActivityDataOnDemand: @Component;
    
    private Random JActivityDataOnDemand.rnd = new SecureRandom();
    
    private List<JActivity> JActivityDataOnDemand.data;
    
    @Autowired
    JCompanyDataOnDemand JActivityDataOnDemand.jCompanyDataOnDemand;
    
    public JActivity JActivityDataOnDemand.getNewTransientJActivity(int index) {
        JActivity obj = new JActivity();
        setCode(obj, index);
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void JActivityDataOnDemand.setCode(JActivity obj, int index) {
        String code = "code_" + index;
        obj.setCode(code);
    }
    
    public void JActivityDataOnDemand.setDescription(JActivity obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void JActivityDataOnDemand.setName(JActivity obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public JActivity JActivityDataOnDemand.getSpecificJActivity(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        JActivity obj = data.get(index);
        Long id = obj.getId();
        return JActivity.findJActivity(id);
    }
    
    public JActivity JActivityDataOnDemand.getRandomJActivity() {
        init();
        JActivity obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return JActivity.findJActivity(id);
    }
    
    public boolean JActivityDataOnDemand.modifyJActivity(JActivity obj) {
        return false;
    }
    
    public void JActivityDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = JActivity.findJActivityEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'JActivity' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<JActivity>();
        for (int i = 0; i < 10; i++) {
            JActivity obj = getNewTransientJActivity(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
