// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.j1987.aakura.domain;

import com.j1987.aakura.domain.JPayment;
import com.j1987.aakura.domain.JPaymentDataOnDemand;
import com.j1987.aakura.domain.JPaymentIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect JPaymentIntegrationTest_Roo_IntegrationTest {
    
    declare @type: JPaymentIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: JPaymentIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: JPaymentIntegrationTest: @Transactional;
    
    @Autowired
    JPaymentDataOnDemand JPaymentIntegrationTest.dod;
    
    @Test
    public void JPaymentIntegrationTest.testCountJPayments() {
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", dod.getRandomJPayment());
        long count = JPayment.countJPayments();
        Assert.assertTrue("Counter for 'JPayment' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void JPaymentIntegrationTest.testFindJPayment() {
        JPayment obj = dod.getRandomJPayment();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to provide an identifier", id);
        obj = JPayment.findJPayment(id);
        Assert.assertNotNull("Find method for 'JPayment' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'JPayment' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void JPaymentIntegrationTest.testFindAllJPayments() {
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", dod.getRandomJPayment());
        long count = JPayment.countJPayments();
        Assert.assertTrue("Too expensive to perform a find all test for 'JPayment', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<JPayment> result = JPayment.findAllJPayments();
        Assert.assertNotNull("Find all method for 'JPayment' illegally returned null", result);
        Assert.assertTrue("Find all method for 'JPayment' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void JPaymentIntegrationTest.testFindJPaymentEntries() {
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", dod.getRandomJPayment());
        long count = JPayment.countJPayments();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<JPayment> result = JPayment.findJPaymentEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'JPayment' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'JPayment' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void JPaymentIntegrationTest.testFlush() {
        JPayment obj = dod.getRandomJPayment();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to provide an identifier", id);
        obj = JPayment.findJPayment(id);
        Assert.assertNotNull("Find method for 'JPayment' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyJPayment(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'JPayment' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JPaymentIntegrationTest.testMergeUpdate() {
        JPayment obj = dod.getRandomJPayment();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to provide an identifier", id);
        obj = JPayment.findJPayment(id);
        boolean modified =  dod.modifyJPayment(obj);
        Integer currentVersion = obj.getVersion();
        JPayment merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'JPayment' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void JPaymentIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", dod.getRandomJPayment());
        JPayment obj = dod.getNewTransientJPayment(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'JPayment' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'JPayment' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'JPayment' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void JPaymentIntegrationTest.testRemove() {
        JPayment obj = dod.getRandomJPayment();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'JPayment' failed to provide an identifier", id);
        obj = JPayment.findJPayment(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'JPayment' with identifier '" + id + "'", JPayment.findJPayment(id));
    }
    
}
